import type { Quest } from './questTypes';

export const KAEL_QUESTS: Quest[] = [
  {
    id: 'kael-01',
    characterId: 'kael',
    title: 'Wood Gatherer',
    description: 'Collect 10 wood.',
    requirements: { wood: 10 },
    reward: { tokens: 1 },
  },
  {
    id: 'kael-02',
    characterId: 'kael',
    title: 'Stone Worker',
    description: 'Collect 5 stone.',
    requirements: { stone: 5 },
    reward: { tokens: 2 },
  },
  {
    id: 'kael-03',
    characterId: 'kael',
    title: 'Iron Worker',
    description: 'Collect 3 iron.',
    requirements: { iron: 3 },
    reward: { tokens: 2 },
  },
  {
    id: 'kael-04',
    characterId: 'kael',
    title: 'Gold Worker',
    description: 'Collect 2 gold.',
    requirements: { gold: 2 },
    reward: { tokens: 2 },
  },
  {
    id: 'kael-05',
    characterId: 'kael',
    title: 'Crystal Worker',
    description: 'Collect 2 crystal.',
    requirements: { crystal: 2 },
    reward: { tokens: 3 },
  },
  {
    id: 'kael-06',
    characterId: 'kael',
    title: 'Wood Supply',
    description: 'Collect 20 wood.',
    requirements: { wood: 20 },
    reward: { tokens: 1 },
  },
  {
    id: 'kael-07',
    characterId: 'kael',
    title: 'Stone Supply',
    description: 'Collect 10 stone.',
    requirements: { stone: 10 },
    reward: { tokens: 4 },
  },
  {
    id: 'kael-08',
    characterId: 'kael',
    title: 'Iron Supply',
    description: 'Collect 6 iron.',
    requirements: { iron: 6 },
    reward: { tokens: 3 },
  },
  {
    id: 'kael-09',
    characterId: 'kael',
    title: 'Gold Supply',
    description: 'Collect 4 gold.',
    requirements: { gold: 4 },
    reward: { tokens: 4 },
  },
  {
    id: 'kael-10',
    characterId: 'kael',
    title: 'Crystal Supply',
    description: 'Collect 4 crystal.',
    requirements: { crystal: 4 },
    reward: { tokens: 5 },
  },

  {
    id: 'kael-11',
    characterId: 'kael',
    title: 'Builder’s Wood',
    description: 'Collect 30 wood.',
    requirements: { wood: 30 },
    reward: { tokens: 1 },
  },
  {
    id: 'kael-12',
    characterId: 'kael',
    title: 'Builder’s Stone',
    description: 'Collect 15 stone.',
    requirements: { stone: 15 },
    reward: { tokens: 6 },
  },
  {
    id: 'kael-13',
    characterId: 'kael',
    title: 'Strong Iron',
    description: 'Collect 9 iron.',
    requirements: { iron: 9 },
    reward: { tokens: 4 },
  },
  {
    id: 'kael-14',
    characterId: 'kael',
    title: 'Golden Materials',
    description: 'Collect 6 gold.',
    requirements: { gold: 6 },
    reward: { tokens: 6 },
  },
  {
    id: 'kael-15',
    characterId: 'kael',
    title: 'Crystal Materials',
    description: 'Collect 6 crystal.',
    requirements: { crystal: 6 },
    reward: { tokens: 7 },
  },
  {
    id: 'kael-16',
    characterId: 'kael',
    title: 'Forest Stock',
    description: 'Collect 40 wood.',
    requirements: { wood: 40 },
    reward: { tokens: 2 },
  },
  {
    id: 'kael-17',
    characterId: 'kael',
    title: 'Mountain Stock',
    description: 'Collect 20 stone.',
    requirements: { stone: 20 },
    reward: { tokens: 8 },
  },
  {
    id: 'kael-18',
    characterId: 'kael',
    title: 'Iron Reserve',
    description: 'Collect 12 iron.',
    requirements: { iron: 12 },
    reward: { tokens: 6 },
  },
  {
    id: 'kael-19',
    characterId: 'kael',
    title: 'Gold Reserve',
    description: 'Collect 8 gold.',
    requirements: { gold: 8 },
    reward: { tokens: 8 },
  },
  {
    id: 'kael-20',
    characterId: 'kael',
    title: 'Crystal Reserve',
    description: 'Collect 8 crystal.',
    requirements: { crystal: 8 },
    reward: { tokens: 10 },
  },

  {
    id: 'kael-21',
    characterId: 'kael',
    title: 'Wood Caravan',
    description: 'Collect 50 wood.',
    requirements: { wood: 50 },
    reward: { tokens: 2 },
  },
  {
    id: 'kael-22',
    characterId: 'kael',
    title: 'Stone Caravan',
    description: 'Collect 25 stone.',
    requirements: { stone: 25 },
    reward: { tokens: 10 },
  },
  {
    id: 'kael-23',
    characterId: 'kael',
    title: 'Iron Caravan',
    description: 'Collect 15 iron.',
    requirements: { iron: 15 },
    reward: { tokens: 8 },
  },
  {
    id: 'kael-24',
    characterId: 'kael',
    title: 'Gold Caravan',
    description: 'Collect 10 gold.',
    requirements: { gold: 10 },
    reward: { tokens: 10 },
  },
  {
    id: 'kael-25',
    characterId: 'kael',
    title: 'Crystal Caravan',
    description: 'Collect 10 crystal.',
    requirements: { crystal: 10 },
    reward: { tokens: 12 },
  },
  {
    id: 'kael-26',
    characterId: 'kael',
    title: 'Great Timber',
    description: 'Collect 60 wood.',
    requirements: { wood: 60 },
    reward: { tokens: 3 },
  },
  {
    id: 'kael-27',
    characterId: 'kael',
    title: 'Great Stone',
    description: 'Collect 30 stone.',
    requirements: { stone: 30 },
    reward: { tokens: 12 },
  },
  {
    id: 'kael-28',
    characterId: 'kael',
    title: 'Great Iron',
    description: 'Collect 18 iron.',
    requirements: { iron: 18 },
    reward: { tokens: 9 },
  },
  {
    id: 'kael-29',
    characterId: 'kael',
    title: 'Great Gold',
    description: 'Collect 12 gold.',
    requirements: { gold: 12 },
    reward: { tokens: 12 },
  },
  {
    id: 'kael-30',
    characterId: 'kael',
    title: 'Great Crystal',
    description: 'Collect 12 crystal.',
    requirements: { crystal: 12 },
    reward: { tokens: 15 },
  },

  {
    id: 'kael-31',
    characterId: 'kael',
    title: 'Master Wood',
    description: 'Collect 70 wood.',
    requirements: { wood: 70 },
    reward: { tokens: 3 },
  },
  {
    id: 'kael-32',
    characterId: 'kael',
    title: 'Master Stone',
    description: 'Collect 35 stone.',
    requirements: { stone: 35 },
    reward: { tokens: 14 },
  },
  {
    id: 'kael-33',
    characterId: 'kael',
    title: 'Master Iron',
    description: 'Collect 21 iron.',
    requirements: { iron: 21 },
    reward: { tokens: 11 },
  },
  {
    id: 'kael-34',
    characterId: 'kael',
    title: 'Master Gold',
    description: 'Collect 14 gold.',
    requirements: { gold: 14 },
    reward: { tokens: 14 },
  },
  {
    id: 'kael-35',
    characterId: 'kael',
    title: 'Master Crystal',
    description: 'Collect 14 crystal.',
    requirements: { crystal: 14 },
    reward: { tokens: 18 },
  },
  {
    id: 'kael-36',
    characterId: 'kael',
    title: 'Royal Timber',
    description: 'Collect 80 wood.',
    requirements: { wood: 80 },
    reward: { tokens: 4 },
  },
  {
    id: 'kael-37',
    characterId: 'kael',
    title: 'Royal Stone',
    description: 'Collect 40 stone.',
    requirements: { stone: 40 },
    reward: { tokens: 16 },
  },
  {
    id: 'kael-38',
    characterId: 'kael',
    title: 'Royal Iron',
    description: 'Collect 24 iron.',
    requirements: { iron: 24 },
    reward: { tokens: 12 },
  },
  {
    id: 'kael-39',
    characterId: 'kael',
    title: 'Royal Gold',
    description: 'Collect 16 gold.',
    requirements: { gold: 16 },
    reward: { tokens: 16 },
  },
  {
    id: 'kael-40',
    characterId: 'kael',
    title: 'Royal Crystal',
    description: 'Collect 16 crystal.',
    requirements: { crystal: 16 },
    reward: { tokens: 20 },
  },

  {
    id: 'kael-41',
    characterId: 'kael',
    title: 'Grand Timber',
    description: 'Collect 100 wood.',
    requirements: { wood: 100 },
    reward: { tokens: 5 },
  },
  {
    id: 'kael-42',
    characterId: 'kael',
    title: 'Grand Stone',
    description: 'Collect 50 stone.',
    requirements: { stone: 50 },
    reward: { tokens: 20 },
  },
  {
    id: 'kael-43',
    characterId: 'kael',
    title: 'Grand Iron',
    description: 'Collect 30 iron.',
    requirements: { iron: 30 },
    reward: { tokens: 15 },
  },
  {
    id: 'kael-44',
    characterId: 'kael',
    title: 'Grand Gold',
    description: 'Collect 20 gold.',
    requirements: { gold: 20 },
    reward: { tokens: 20 },
  },
  {
    id: 'kael-45',
    characterId: 'kael',
    title: 'Grand Crystal',
    description: 'Collect 20 crystal.',
    requirements: { crystal: 20 },
    reward: { tokens: 25 },
  },
  {
    id: 'kael-46',
    characterId: 'kael',
    title: 'Founder’s Wood',
    description: 'Collect 120 wood.',
    requirements: { wood: 120 },
    reward: { tokens: 6 },
  },
  {
    id: 'kael-47',
    characterId: 'kael',
    title: 'Founder’s Stone',
    description: 'Collect 60 stone.',
    requirements: { stone: 60 },
    reward: { tokens: 24 },
  },
  {
    id: 'kael-48',
    characterId: 'kael',
    title: 'Founder’s Iron',
    description: 'Collect 36 iron.',
    requirements: { iron: 36 },
    reward: { tokens: 18 },
  },
  {
    id: 'kael-49',
    characterId: 'kael',
    title: 'Founder’s Gold',
    description: 'Collect 24 gold.',
    requirements: { gold: 24 },
    reward: { tokens: 24 },
  },
  {
    id: 'kael-50',
    characterId: 'kael',
    title: 'Founder’s Crystal',
    description: 'Collect 24 crystal.',
    requirements: { crystal: 24 },
    reward: { tokens: 30 },
  },
];